version: '3.8'

services:
  backend:
    container_name: gamelist-backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 5070:5070

  frontend:
    container_name: gamelist-frontend
    image: frontend
    ports:
      - 3000:3000
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
      args:
        - API_URL=http://localhost:5070
    depends_on:
      - backend
