// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Gamedbinfo struct {
	GameInfo        int32
	IgdbID          string
	MetacriticScore int32
	SteamID         string
}

type Gameinfo struct {
	ID          int32
	Name        string
	Description string
	Genres      []string
	ArtworkUrl  pgtype.Text
	ReleaseDate pgtype.Date
}

type Gamelist struct {
	ID   int32
	Name string
}

type Gamestate struct {
	GameInfo     int32
	GameList     pgtype.Int4
	UserRating   int32
	GametimeMin  int32
	ListOrder    int32
	CustomStatus string
	LastPlayed   pgtype.Date
}
